name: Deploy to Specific Target

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["WebServer1", "WebServer2"] # Define specific deployment targets
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Make the script executable
      - name: Prepare deployment script
        run: chmod +x deploy.sh

      # Step 3: Run the deployment script for the specific target
      - name: Deploy to ${{ matrix.target }}
        run: ./deploy.sh ${{ matrix.target }}
        env:
          APP_VERSION: "1.0.0" # Example of passing additional environment variables
